name: Publish packages

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Set VERSION variable
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Debug --no-restore /p:Version=${VERSION}
      - name: Pack
        run: dotnet pack -c Debug --no-build --output packags /p:Version=${VERSION}
      - name: Push packages to NuGet
        run: dotnet nuget push "packags/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key=${{secrets.NUGET_API_KEY}}
